name: Build Release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Installing musl rust toolchain
      run: rustup target add x86_64-unknown-linux-musl
    - run: sudo apt-get install musl-tools
    - name: Build release
      run: cargo build --bin SRXDManager --target x86_64-unknown-linux-musl --release
    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: SRXDManager-linux-musl
        path: target/x86_64-unknown-linux-musl/release/SRXDManager
